ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story2.urls', namespace='story2')),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story9/urls.py
from django.urls import path

from . import views

app_name = "story8"
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.user_login, name='login'),
    path('signup', views.user_signUp, name='signup'),
    path('logout', views.logout_user, name='logout'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm


# Create your views here.


def index(request) :
    return render(request, 'story9/index.html')

def user_login(request) :
    if request.user.is_authenticated:
        return redirect('story9:index')
    if request.method == "POST" :
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('story9:index')
        else :
            context = {'failed': 'please check ur username or password'}
            return render(request, 'story9/login.html', context)
    return render(request, 'story9/login.html')

def user_signUp(request) :
    form = UserCreationForm()
    if request.user.is_authenticated:
        return redirect('story9:index')

    if request.method == "POST" :
        form = UserCreationForm(request.POST)
        if form.is_valid() :
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'],)
            login(request, new_user)
            return redirect('story9:login')

    context = {'form' : form}
    return render(request, 'story9/signup.html', context)

def logout_user(request) :
    logout(request)
    return redirect('story9:index')

story9/templates/story9/index.html
{% extends 'story4/base.html'%}

<!DOCTYPE html>
{% load static %}
<head>
    {% block title%}
    <title>Story 9</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    

    {% block css %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    
    

    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">

    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <nav class='navbar navbar-expand navbar-custom fixed-top'>
        {% block navbar%}
        <ul class='nav navbar-nav' style="margin-left:auto">
            {% if user.is_authenticated %}
            <li class='nav-item'>
                <a  class='nav-link page-scroll'> {{ user.username}} </a>
            </li>
            <li class='nav-item'>
                <a href="{%url 'story9:logout' %}" class='nav-link page-scroll'> Log Out </a>
            </li>
            
            
            {% else %}

            <li class='nav-item'>
                <a href="{%url 'story9:login' %}"  class='nav-link page-scroll'> Login </a>
            </li>

            <li class='nav-item'>
                <a href="{%url 'story9:signup' %}"  class='nav-link page-scroll'> Sign Up </a>
            </li>
            
            {% endif %}
        </ul>
        {% endblock %}
        
        
    </nav>
    {% block content %}
    {% if user.is_authenticated %}

    <div class="container-fluid text-center" style="background-color:#E9ECEF ; min-height: 100vh;">
        <div class="row justify-content-center" >
            <div class='col-12' style="text-align: center; padding-top:10%; ">
                <h1>Hello, {{user.username}}</h1>
            </div>
        </div>
        <br>
    </div>

    {%else%}

    <div class="container-fluid text-center" style="background-color:#E9ECEF ; min-height: 100vh;">
        <div class="row justify-content-center" >
            <div class='col-12' style="text-align: center; padding-top:10%; ">
                <h1>Please Login</h1>
            </div>
        </div>
        <br>
    </div>
    
    {% endif %}


    {% endblock %}
</body>
</html>

story9/templates/story9/login.html
{% extends 'story4/base.html'%}

<!DOCTYPE html>
{% load static %}
<head>
    {% block title%}
    <title>Story 9</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    

    {% block css %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    
    

    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">

    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <nav class='navbar navbar-expand navbar-custom fixed-top'>
        {% block navbar%}
        <ul class='nav navbar-nav' style="margin-left:auto">
            {% if user.is_authenticated %}
            <li class='nav-item'>
                <a  class='nav-link page-scroll'> {{ user.username}} </a>
            </li>
            <li class='nav-item'>
                <a href="{%url 'story9:logout' %}" class='nav-link page-scroll'> Log Out </a>
            </li>
            
            
            {% else %}

            <li class='nav-item'>
                <a href="{%url 'story9:login' %}"  class='nav-link page-scroll'> Login </a>
            </li>

            <li class='nav-item'>
                <a href="{%url 'story9:signup' %}"  class='nav-link page-scroll'> Sign Up </a>
            </li>
            
            {% endif %}
        </ul>
        {% endblock %}
        
        
    </nav>
    {% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        
        <div class="container text-center">
            <div class="row">
                <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                    <h1>Login</h1>
                </div>
            </div>

            
            
            <div class="border border-light" style="padding: 5%; margin:5% auto; width: 400px;">
                
                {% if failed %}

                <div class="alert alert-danger" role="alert">
                    <p class=lead style='font-size:small; margin-bottom: 0;'> invalid username or password! </p> 
                </div>

                {% endif %}
                <div class="row justify-content-center form-group " style="">
                    <div class=col-12>
                        <label for="username">Username:</label><br>
                        <input type="text" class="form-control" name="username"><br>
                        <label for="password">Password:</label><br>
                        <input type="password" class="form-control" name="password"> <br>
                        <button type="submit" name="login" value="login" class="btn btn-dark btn-block">Login</button>
                    </div>                
                </div>
            </div>

            
        </div>
    </form>
    



    {% endblock %}
</body>
</html>

story9/templates/story9/signup.html
{% extends 'story4/base.html'%}

{% load crispy_forms_tags %}
<!DOCTYPE html>
{% load static %}
<head>
    {% block title%}
    <title>Story 9</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    

    {% block css %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    
    

    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">

    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <nav class='navbar navbar-expand navbar-custom fixed-top'>
        {% block navbar%}
        <ul class='nav navbar-nav' style="margin-left:auto">
            {% if user.is_authenticated %}
            <li class='nav-item'>
                <a  class='nav-link page-scroll'> {{ user.username}} </a>
            </li>
            <li class='nav-item'>
                <a href="{%url 'story9:logout' %}" class='nav-link page-scroll'> Log Out </a>
            </li>
            
            
            {% else %}

            <li class='nav-item'>
                <a href="{%url 'story9:login' %}"  class='nav-link page-scroll'> Login </a>
            </li>

            <li class='nav-item'>
                <a href="{%url 'story9:signup' %}"  class='nav-link page-scroll'> Sign Up </a>
            </li>
            
            {% endif %}
        </ul>
        {% endblock %}
        
        
    </nav>
    {% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        
        <div class="container text-center">
            <div class="row">
                <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                    <h1>Sign Up</h1>
                </div>
            </div>

            
            
            <div class="border border-light" style="padding: 5%; margin:5% auto; width: 600px;">
                
                {% if failed %}

                <div class="alert alert-danger" role="alert">
                    <p class=lead style='font-size:small; margin-bottom: 0;'> invalid username or password! </p> 
                </div>

                {% endif %}
                <div class="row justify-content-center form-group " style="">
                    <div class=col-12>
                        {{form | crispy}}
                        <button type="submit" name="signup" value="signup" class="btn btn-dark btn-block">Login</button>
                    </div>                
                </div>
            </div>

            
        </div>
    </form>
    

    
    

    {% endblock %}
</body>
</html>