ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story2.urls', namespace='story2')),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

story4/models.py
from django.db import models

# Create your models here.

story4/views.py
from django.shortcuts import render,redirect

# Create your views here.

def index(request) :
    return redirect('story1:index')

story4/templates/story4/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    

    {% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story4/style.css' %}">
    {% endblock %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Document</title>
    {% endblock %}
</head>
<body>

    
    <nav class='navbar navbar-expand navbar-custom fixed-top'>
        <ul class='nav navbar-nav'>
            <li class='nav-item'>
                <a href="{% url 'story1:index' %}"  class='nav-link'> Story 1 </a>
            </li>
            <li class='nav-item'>
                <a href="{% url 'story2:index' %}"  class='nav-link'> Story 3 </a>
            </li>
            <li class='nav-item'>
                <a href="{% url 'story5:index' %}"  class='nav-link'> Story 5 </a>
            </li>

            <li class='nav-item'>
                <a href="{% url 'story6:index' %}"  class='nav-link'> Story 6 </a>
            </li>

            <li class='nav-item'>
                <a href="{% url 'story7:index' %}"  class='nav-link'> Story 7 </a>
            </li>

            <li class='nav-item'>
                <a href="{% url 'story8:index' %}"  class='nav-link'> Story 8 </a>
            </li>

            <li class='nav-item'>
                <a href="{% url 'story9:index' %}"  class='nav-link'> Story 9 </a>
            </li>
        </ul>

            {% block navbar%}
            {% endblock %}
    </nav>

    {% block content %}
    {% endblock %}
    <footer class="footer">
        <div class="container-fluid text-center" style="background-color: #F5EFEF;">
            <div class="row ">
                <div class="col-12 col-md-12">
                    <br>
                    <br>
                    <p>Contact Me!</p>
                    <h1>RAFI MUHAMMAD</h1>
                    <hr style="width: 20%; margin: auto; border-top: 2px solid #000000;">
                </div>
            </div>
            <br>
    
            <div class='row justify-content-center'>
                <div style="margin: 1%; margin-bottom: 5%;"> <a href="https://www.linkedin.com/in/rafi-muhammad-b89b30198/"><img src="{% static 'story2/linkedin 1.png' %}" alt="" style="margin: 0%;"></a> </div>
                <div style="margin: 1%;"><img src="{% static 'story2/gmail 1.png' %}" alt="" style="margin: 0%;"></a> </div>
                <div style="margin: 1%;"> <a href="https://github.com/rafimuhammad01"> <img src="{% static 'story2/github-logo 1.png' %}" alt="" style="margin: 0%;"> </a> </div>
                <br>
                <br>
            </div>

        
            
        </div>
    </footer>
        
</body>
</html>