ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story2.urls', namespace='story2')),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story5/urls.py
from django.urls import path

from . import views
app_name = "story5"
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('update/<int:id>', views.update, name='update'),
    path('detail/<int:id>', views.detail, name='detail')
]

story5/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model) :
    nama_matkul = models.CharField(max_length = 50)
    semester = models.CharField(max_length = 50)
    deskripsi = models.TextField(max_length = 500)
    sks = models.CharField(max_length = 50)

    def __str__(self) :
        return self.nama_matkul

story5/forms.py
from django import forms

from .models import MataKuliah

class MataKuliahForm(forms.ModelForm):


    class Meta :
        model = MataKuliah
        fields = [
            'nama_matkul',
            'semester',
            'sks',
            'deskripsi'
        ]

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import MataKuliah
from .forms import MataKuliahForm

# Create your views here.

def index(request) :
    mataKuliah = MataKuliah.objects.order_by("semester")
    

    if request.POST.get('add') :
        return redirect('story5:add')

    context = {
        "mataKuliah" : mataKuliah,
    }
    return render(request, 'story5/index.html', context)

def add(request) :
    form = MataKuliahForm()
    if request.method == "POST" :
        form = MataKuliahForm(request.POST)
        if form.is_valid() :
            form.save()
            return redirect('story5:index')
    context = {
        "form" : form
    }
    return render(request, 'story5/add.html', context)

def detail(request, id) :
    mataKuliah = MataKuliah.objects.get(id=id)
    if request.POST.get('update') :
        return redirect('story5:update', request.POST.get('update'))
    if request.POST.get('delete') :
        MataKuliah.objects.get(id=request.POST.get('delete')).delete()
        return redirect('story5:index')
    context = {
        'mataKuliah' : mataKuliah
    }
    return render(request, 'story5/detail.html', context)

def update(request, id) :
    form = MataKuliahForm(instance=MataKuliah.objects.get(id=id))
    if request.method == "POST" :
        form = MataKuliahForm(request.POST, instance=MataKuliah.objects.get(id=id))
        if form.is_valid() :
            form.save()
            return redirect('story5:index')
    context = {
        "form" : form,
        "update" : True
    }
    return render(request, 'story5/add.html', context)

story5/templates/story5/add.html
{% extends 'story4/base.html'%}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    {% block title%}
    <title>Profile</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    {% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



    {% block content %}
    <div class='container text-center'>
        <div class="row">
            <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                <h1> Tambah Mata Kuliah </h1>
            </div>
        </div>
        <br>
        <div class='form-group'>
            <form action="", method='POST'>
                {% csrf_token %}
                {{form | crispy}}

                {% if update %}
                    <button type="submit" name= "update" value= "update" class="btn btn-dark btn-lg btn-block">Update</button>
                {% else %}
                    <button type="submit" name= "add" value= "add" class="btn btn-dark btn-lg btn-block">Add</button>
                {% endif %}
            </form>
        </div>
        
    </div>

    {% endblock %}    
    
    
</body>
</html>

story5/templates/story5/detail.html
{% extends 'story4/base.html'%}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    {% block title%}
    <title>Mata Kuliah</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    {% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



    {% block content %}
    <div class='container text-center'>
        <div class="row">
            <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                <h1> Detail Mata Kuliah </h1>
            </div>
        </div>
        <br>
        <div class="border border-light">
            <div class='row' style=" text-align: left ;">
                
                <div class='col-12 col-md-12'>
                    
                    <form action="", method='POST'>
                        {% csrf_token %}
                        <h1 style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%">{{mataKuliah.nama_matkul}}</h1>
                        <p> Semester {{mataKuliah.semester}} - {{mataKuliah.sks}} SKS</p>
                        <p style="margin: 0%;"> {{ mataKuliah.deskripsi }} </p> <br> 
                        <button type="submit" name="update" value="{{mataKuliah.id}}" class="btn btn-dark">Update</button>
                        <button type="submit" name= "delete" value= "{{mataKuliah.id}}" class="btn btn-dark">Delete</button>
                    </form>
                    

                    
                </div>
            </div>
        </div>
        
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    {% endblock %}    
    
    
</body>
</html>

story5/templates/story5/index.html
{% extends 'story4/base.html'%}

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    {% block title%}
    <title>Profile</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    {% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



    {% block content %}
    <div id="projects">
        <div class='container text-center'>
            <form action="", method='POST'>
                <div class="row">
                    <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                        <h1> Daftar Mata Kuliah </h1>
                    </div>
                </div>
                
                <div class="border border-light">
                    <div class='row' style=" text-align: left ;">
                        
                            {% csrf_token %}
                            {% if mataKuliah %}
                                {% for i in mataKuliah %}

                                    <div class='col-12 col-md-12'>
                                        <a href="{% url 'story5:detail' i.id %}" style="text-align: left;font-size: x-large; padding-bottom: 0; padding-top:3%; ">{{i.nama_matkul}}</a>
                                        <hr>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class='col-12 col-md-12'>
                                    <br><br><br><br>
                                    <h1 style="text-align: center; font-size: x-large;justify-content: center;">EMPTY</h1>

                                </div>
                                <br><br><br><br><br><br><br><br><br><br><br><br>
                            {% endif %}

                        
                    </div>
                </div>
    
                <div class="row">
                    <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                        <button type="submit" name="add" value="add" class="btn btn-dark btn-lg btn-block">ADD</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    {% endblock %}    
    
    
</body>
</html>

story5/templates/story5/update.html
{% extends 'story4/base.html'%}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    {% block title%}
    <title>Profile</title>
    {% endblock %}
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    {% block css %}
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'story2/style.css' %}">
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



    {% block content %}
    <div class='container text-center'>
        <div class="row">
            <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                <h1> Update Mata Kuliah </h1>
            </div>
        </div>
        <br>
        <div class='form-group'>
            <form action="", method='POST'>
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" name= "add" value= "add" class="btn btn-dark btn-lg btn-block">Add</button>
            </form>
        </div>
        
    </div>

    {% endblock %}    
    
    
</body>
</html>